### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by deepak-thakur**
# Fill out the following while publishing a new pull request.

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:

### CODE REVIEW

**Comment by groverankush** [comment]
Is it required right now?

**Comment by KamalMrock** [comment]
Of course not.

**Comment by groverankush** [comment]
I guess everyone is just working on develop branch. So why not merge it as we're done with the project. What do you say?

**Comment by KamalMrock** [comment]
Yeah

**Pull request closed without merging**
