### PR TITLE
Donor and Receiver details shown on click on marker on map related to…

### PR DESCRIPTION
**Pull request by omi90**
… Issue no #103 and #104

# Fill out the following while publishing a new pull request.

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Enhancement

* **What is the current behavior?** (You can also link to an open issue here)
Initially there was no details shown of the donors or requestors when user clicks on a marker on map.

* **What is the new behavior (if this is a feature change)?**
On Clicking on marker on map Name , Blood Group, Purpose and clickable Phone number will be displayed in bottom sheet.

### CODE REVIEW

**Comment by omi90** [comment]
image
image

**Comment by KamalMrock** [comment]
@omi90 That's a fantastic job.

**Comment by KamalMrock** [comment]
What if we add Route option at the place of phone number By clicking on Route Google map should open and show route between donor and receiver.

**Comment by omi90** [comment]
@KamalMrock added a Get Direction button.
image

**Comment by KamalMrock** [comment]
Great.

**Comment by KamalMrock** [comment]
@omi90 there is no get direction button for Donor sheet.
Add this to ASAP
Send pr to master now.

**Comment by omi90** [comment]
@KamalMrock Already added.

**Comment by KamalMrock** [comment]
And one thing more @omi90 
Replace phone no. With call button.

I mean "Call" button instead of this +918586856857

And put "Get Direction button little lower.
ASAP.

**Comment by KamalMrock** [comment]
@omi90 any update?

**Pull request merged**
