### PR TITLE
Fix userdetails layout

### PR DESCRIPTION
**Pull request by intkhabahmed**
# Fill out the following while publishing a new pull request.

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Restored the user details layout design with some improvements

* **What is the current behavior?** (You can also link to an open issue here)
The current design was disturbed during integrating with the code

* **What is the new behavior (if this is a feature change)?**
It restores the design of user details layout with some improvements

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
No

* **Other information**:
**Old Design**

**Improved design**

### CODE REVIEW

**Comment by intkhabahmed** [comment]
@ritesh-singh I have fixed the layout, the functioning is same, you can merge it

**Comment by nipunjindal** [comment]
@intkhabahmed: what value do you get by moving to ContraintLayout, to me it appears that the LinearLayout works pretty well on all screen sizes here. Could you point out something that I am missing? (Your layouting looks good, howwever isn't that possible by far few changes with the earlier code itself)

**Comment by intkhabahmed** [comment]
@nipunjindal This was the design which was first updated, but while integrating the code, ritesh removed this design with the previois design which was not looking good, so I restored the old design with some extra icons and spacing.
The advantage of constraint layout over linear layout is that you don't need to nest views to place in the current poaitions. If you see the code the view hierarchy is two level down in constraint layout version i.e ScrollView - > ConstraintLayout - > views
But if you use linear layout it will be like
ScrollView - >( linearLayout->views) + views + (LinearLayout - > views) +views
So we should always try to make our hierarchy as flat as possible and it is achieved by Constraint Layout

**Comment by nipunjindal** [comment]
@intkhabahmed: what do we achieve with flat hierarchy here? (This might not affect the current PR, however, I am just trying to understand if this is something which was done for a reason)

**Comment by intkhabahmed** [comment]
Give a reas on this page and you will understand

https://android-developers.googleblog.com/2017/08/understanding-performance-benefits-of.html?m=1

**Comment by nipunjindal** [comment]
@intkhabahmed: Sure, makes sense now. Thanks for sharing.
Just to share, it's weird though, AutoLayouting on iOS works completely on constraints, however, they mention using StackViews(Kinds of like LinearLayout), where ever possible, considering the ease it provides.
But if performance is the concern in Android, ConstraintLayout looks good!

**Pull request merged**
