### PR TITLE
Develop fix

### PR DESCRIPTION
**Pull request by ritesh-singh**
# Fill out the following while publishing a new pull request.

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Fixed develop broken branch
Added permission util

* **What is the current behavior?** (You can also link to an open issue here)
No change in behavior

* **What is the new behavior (if this is a feature change)?**
No change

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
Nope

* **Other information**:

### CODE REVIEW

**Comment by tavishjain** [comment]
@ritesh-singh I haven't understood the code that you have written. Could you simplify it ?? Or just make changes to stop memory leak in my code?

**Comment by ritesh-singh** [comment]
@tavishjain Which part of code, you didnt understood. Is it the AppPermissionsUtil?

**Comment by tavishjain** [comment]
@ritesh-singh yes .

**Comment by ritesh-singh** [comment]
Okay, what are you not able understand in that class.
ContextCompat.checkSelfPermission is for checking dangerous permissions if it's allowed for the app or not.

ActivityCompat.requestPermissions is for requesting the permissions.

And <T extends AppCompatActivity> is a generic method with upper bound as AppCompatActivity, ant activity extending this, will be acceptable.

**Pull request merged**
